apiVersion: v1
kind: Pod
metadata:
 name: queue-pod
 labels:
   queue-service: queue-service
   version: "0-1"
spec:
  containers:
    - name: queue-service
      image: richardchesterwood/k8s-fleetman-queue:release1