apiVersion: v1
kind: Service
metadata:
 name: queue-pod
spec:
  selector:
    queue-service: queue-service
    version: "0-1"
  ports:
   - name: console-http
     port: 8161
     nodePort: 30010
  type: NodePort